name: batra
favicon: null
layout_spectrum: 0.05027064913883805
typography_spectrum: 0.35065405489876866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.17874394170939922
  lightness: 0.8049144444521517
  saturation: 0.4164153707679361
  rhythmicContrast: 0.13618000084534287
purpose: []
